<?php

return array(
    /**
     * Default Parameters
     *
     * These parameters are required for your JMAP server to operate.
     * Do not edit this file. Copy + paste it to config/config.php and then edit instead.
     */

    // ********************** //
    /// General configuration
    // ********************** //

    // Admin users for Webclient admin auth. Users should exist on the webclient and belong to the same domain.
    'adminUsers' => array('yourchosenadminuser'),

    // Enabled capabilities for this endpoint
    'capabilities' => array('jscontact', 'mail'),

    // ********************** //
    /// Logging configuration
    // ********************** //
    // NOTE: Only a single logger will be used

    // Print verbose error output via API for debugging
    // NOTE: Not recommended on public-facing setups
    'verboseErrorOutput' => false,

    // Allow File logger (also as fallback in case no other is working)
    'allowFileLog' => false,

    // Allow Graylog logger (in case gelf-php included under vendor/)
    'allowGraylog' => false,

    // PSR 3 minimum log level
    'logLevel' => \Psr\Log\LogLevel::WARNING,

    // FileLogger's path to log file relative to this dir
    'fileLogPath' => __DIR__ . '/../log.log',

    // Graylog endpoint to use
    'graylogEndpoint' => '',

    // Graylog Port to use
    'graylogPort' => 12201,

    // Allow self-signed certs
    'graylogAllowSelfSigned' => false,

    // Use TLS
    'graylogUseTls' => true,

    // Method of handling broken vCards
    // Possible values:
    // 'strict',
    // 'ignoreInvalidLines',
    // 'ignoreInvalidVCards'
    // WARNING: Changing this will ignore certain error cases and may cause data loss
    'vCardParsing' => 'strict',

    // Allow logging of entire vCards when broken
    'dumpInvalidVCards' => false
);
